spring:
  datasource:
    url: jdbc:mysql://iteams_db:3306/it_eams_prod?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}

logging:
  level:
    root: warn
    io.nssa.iteams: info