# =============================================
# IT资产管理系统应用配置文件
# 包含：服务器、数据库、JPA、认证、任务执行器和安全配置
# =============================================

server:
  port: 8080                        # 应用服务端口号
  servlet:
    context-path: /                 # 应用上下文路径，表示根路径
  compression:
    enabled: true                   # 启用HTTP响应压缩，减少网络传输量

spring:
  application:
    name: it-asset-management       # 应用名称，用于日志和监控识别
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  
  # 数据源配置
  # 定义与MySQL数据库的连接参数和连接池设置
  datasource:
    url: jdbc:mysql://localhost:3306/iteams_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
                                    # 数据库连接URL：
                                    # - 使用Unicode编码支持中文
                                    # - 使用UTF-8字符集
                                    # - 禁用SSL连接（仅在测试环境，生产应启用）
                                    # - 设置时区为上海
                                    # - 允许公钥检索用于安全连接
    username: root                  # 数据库用户名
    password: root            # 数据库密码（生产环境应使用加密配置）
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 8.0+驱动类
    hikari:                         # Hikari连接池配置，Spring Boot默认连接池
      maximum-pool-size: 20         # 最大连接数，根据并发量调整
      minimum-idle: 5               # 最小空闲连接数
      connection-timeout: 30000     # 连接超时时间（毫秒）
  
  # 数据库初始化配置
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # 数据库方言，适用于MySQL 8.0+
    hibernate:
      ddl-auto: update              # 自动创建/更新表结构
    show-sql: true                  # 显示SQL语句，方便开发调试
    properties:
      hibernate:
        format_sql: true            # 格式化SQL日志输出，提高可读性
        dialect: org.hibernate.dialect.MySQLDialect  # 数据库方言，适用于MySQL 8.0+
        jdbc:
          batch_size: 50            # JDBC批处理大小，提高批量操作性能
    defer-datasource-initialization: true # 确保在JPA初始化后再执行SQL脚本
  
  # 文件上传配置
  # 用于限制Excel导入文件的大小和请求参数
  servlet:
    multipart:
      enabled: true                 # 启用文件上传功能
      max-file-size: 10MB           # 单个文件最大大小（10MB）
      max-request-size: 15MB        # 请求总体积最大大小（15MB）
      file-size-threshold: 2MB      # 文件大小阈值，超过后写入磁盘临时文件
  
  # 异步任务执行器
  # 用于处理后台任务，如Excel导入和数据处理
  task:
    execution:
      pool:
        core-size: 5                # 核心线程数，常驻线程数量
        max-size: 10                # 最大线程数，高峰期最大线程数
        queue-capacity: 25          # 任务队列容量，超过后创建新线程
        keep-alive: 60s             # 线程空闲存活时间，超时回收
      thread-name-prefix: async-task-  # 线程名前缀，用于日志区分

# 自定义配置项
# 项目特定的参数配置
iteams:
  import:
    template-path: classpath:templates/import_template.xlsx
                                    # Excel导入模板文件路径
    batch-size: 100                 # 每批处理的记录数，用于大批量导入优化
    keep-days: 30                   # 导入历史保留天数，过期自动清理
  security:
    jwt:
      secret-key: eamsSecretKey2025ITAssetManagementSystemSecretKeyForJWT
                                    # JWT密钥，用于生成和验证令牌（生产环境应加密保存）
      token-validity-in-seconds: 86400
                                    # 令牌有效期，单位秒（24小时）
      token-validity-in-seconds-for-remember-me: 604800
                                    # "记住我"选项的令牌有效期（7天）
  # 用户服务配置
  user:
    service-url: http://localhost:8080/api
                                    # 用户管理服务API地址
                                    
  # 初始化数据配置
  init-data:
    # 是否启用初始化数据
    enabled: true
    # 角色配置
    roles:
      - name: 超级管理员
        code: SUPER_ADMIN
        description: 系统超级管理员，拥有所有权限
      - name: 管理员
        code: ADMIN
        description: 系统管理员角色，拥有大部分管理权限
      - name: 普通用户
        code: USER
        description: 系统基本用户角色，拥有基本操作权限
    # 超级管理员用户配置
    admin-user:
      username: supadmin
      password: $2a$10$0WPWBaXQvZ7SuUViXN5vSevqGLP8/i3rCsB6jyB8g78qH1emPukmK
      password-encrypted: true
      real-name: 系统管理员
      email: admin@iteams.com
      department: 系统管理部
      role-code: SUPER_ADMIN

# JWT配置
# 用于JWT令牌的生成和验证
jwt:
  # JWT密钥（生产环境应使用更复杂的密钥并通过环境变量注入）
  secret: eamsSecretKey2025ITAssetManagementSystemSecretKeyForJWT
  # JWT过期时间（24小时，单位：毫秒）
  expiration: 86400000
  # 记住我过期时间（7天，单位：毫秒）
  remember-me-expiration: 604800000

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.iteams: DEBUG
